### ISSUE TITLE
Source code of the demo application

### ISSUE THREAD

**Issue by XvAK** [vaadin/collaboration-engine#25]
Can the source code of the demo application be made public?

https://collaboration-engine.demo.vaadin.com/

I know it's not much different from the "starter" app, however I am interested in this little app.

**Comment by Peppe** [comment]
Hi. 

Sure. It was not meant to be public, but I don't see much harm in making it public. As the code was not meant to originally be public, it might have some shortcuts, or unoptimized code.

You can now find it at https://github.com/vaadin/ce-demo. It is a project from [Vaadin Start](https://start.vaadin.com/), with added Collaboration Engine features.

#### Redesign of the app

Note that I'm doing an overhaul to the app at this very moment. You can find the new version in the [comments](https://github.com/vaadin/ce-demo/tree/comments) -branch. 

The changes so far in that branch: 
- Updates from Vaadin 14 to Vaadin 20
- Changes the visual look
- Uses new theming mechanism instead of shared-styles.js
- Uses class names for theming instead of custom css
- Moves the editor to popup
- Adds a chat feature
- Changes main entity from Person to Employee
- Cleans up the code, and maybe more. 

There are still some issues with the new fields in the editor and how the bot edits data. I hope I can finish this work this week.

#### Current looks of the app, on master.
<img width="1428" alt="Screen Shot 2021-03-24 at 8 35 11" src="https://user-images.githubusercontent.com/525503/112266723-18cfbc00-8c7d-11eb-90d0-4041c703ffad.png">
<img width="1428" alt="Screen Shot 2021-03-24 at 8 35 17" src="https://user-images.githubusercontent.com/525503/112266733-1b321600-8c7d-11eb-96c2-10d772271145.png">

#### New look in the 'Comments' branch
<img width="1428" alt="Screen Shot 2021-03-24 at 8 29 02" src="https://user-images.githubusercontent.com/525503/112266793-2f761300-8c7d-11eb-85e1-2753dd622a03.png">
<img width="1428" alt="Screen Shot 2021-03-24 at 8 29 16" src="https://user-images.githubusercontent.com/525503/112266808-34d35d80-8c7d-11eb-95cf-c69ca8941139.png">
